# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tesco}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["JP Hastings-Spital"]
  s.date = %q{2010-07-22}
  s.description = %q{Search the Tesco Groceries API, through a very object oriented library}
  s.email = %q{jphastings@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Rakefile",
     "VERSION",
     "lib/tesco.rb",
     "readme.md"
  ]
  s.homepage = %q{http://github.com/jphastings/TescoGroceries}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An extremely straightforward library for the Tesco Grocery API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

